### ISSUE TITLE
HTML5 GeoLocation 정확도 개선

### ISSUE THREAD

**Issue by tom9744** [UmileVX/vx-UmileVX_webClient#3]
@KimYoonSoo 수석님께서 보내주신 메일 확인하였으며, Github Issue로 남겨 놓습니다.

아무래도 처음에 HTTPS가 적용되지 않은 상황 아래 로컬 환경에서 기능 테스트를 수행하는 과정에서
현재 위치를 불러오는데 너무 많은 시간이 소요되어 `enableHighAccuracy`라는 GeoLocation 옵션을 `false`로 설정했기 때문일 것입니다.

```javascript
// HTML5 GeoLocation API Option 값
const options = {
  enableHighAccuracy: true,
  maximumAge: 0,
  timeout: 10000
};
```
위의 예시와 같이 소스를 변경 후 테스트 해보는 것이 좋을 것 같습니다.

**Comment by KimYoonSoo** [comment]
@tom9744 
네~ 알겠습니다. 정보 공유 고맙습니다.
수정 되시면 이야기 부탁드립니다. 다시 테스트해 보겠습니다.

**Comment by tom9744** [comment]
@KimYoonSoo 

`enableHighAccuracy` 항목의 설정값을 `true`로 변경하여 최선의 GPS 정확도를 가지도록 하였습니다.
기기의 GPS 종류, 인터넷 연결 상태 등에 따라 GPS 위치 정보를 가져오는 데 소요되는 시간은 천차만별이 될 것입니다.
GeoLocation API 관련 정보를 찾아보면, 길게는 5-10분까지도 소요될 수 있다고 합니다. 

마냥 기다릴 수는 없는 것이기에, `timeout`을 10초로 설정하여 기준시간보다 더 긴 시간이 소요되는 경우
GPS를 사용한 위치 정보 가져오기를 멈추고 지도에서 수동으로 선택하도록 구성하였습니다.

`timeout`의 설정값은 고객사 / 프로젝트 팀 회의에서 도출된 값을 사용하도록 변경하는 것이 좋을 것 같습니다.

**Comment by tom9744** [comment]
해결 완료
